# Generated by Django 3.2.8 on 2022-01-22 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='КОЛИЧЕСТВО')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='ДОБАВЛЕНО')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='ОБНОВЛЕНО')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='ТОВАР')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL, verbose_name='ПОЛЬЗОВАТЕЛЬ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы пользователей',
            },
            bases=(mainapp.mixins.ProductQuantityMixin, models.Model),
        ),
    ]
