# Generated by Django 3.2.8 on 2022-02-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ('pk',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы пользователей'},
        ),
    ]
