# Generated by Django 3.2.8 on 2022-01-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='КАТЕГОРИЯ')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ОПИСАНИЕ')),
                ('is_active', models.BooleanField(default=True, verbose_name='АКТИВЕН')),
            ],
            options={
                'verbose_name': 'КАТЕГОРИЯ',
                'verbose_name_plural': 'КАТЕГОРИИ',
                'ordering': ('slug', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='ТОВАР')),
                ('image', models.ImageField(blank=True, upload_to='product_image', verbose_name='ИЗОБРАЖЕНИЕ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ОПИСАНИЕ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ЦЕНА')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='КОЛИЧЕСТВО')),
                ('is_active', models.BooleanField(default=True, verbose_name='АКТИВЕН')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory', verbose_name='КАТЕГОРИЯ')),
            ],
            options={
                'verbose_name': 'ТОВАР',
                'verbose_name_plural': 'ТОВАРЫ',
                'ordering': ('id',),
            },
        ),
    ]
